# -*- coding: utf-8 -*-
"""Pre-Processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0nM5Uc5SPNZJCmb6fWg64-nIJZ6YEih
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('/content/Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

print("X \n",x)
print("Y \n",y)

from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan ,strategy='mean')
imputer.fit(x[:,1:3])
(x[:,1:3])=imputer.transform(x[:,1:3])

print("X \n",x)
print("Y \n",y)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

print("X \n",x)
print("Y \n",y)

from sklearn.model_selection import train_test_split
xtr,xt,ytr,yt=train_test_split(x,y,test_size=0.2,random_state=1)

print("X Train - \n",xtr)
print("Y Train - \n",ytr)
print("X Test - \n",xt)
print("Y Test - \n",yt)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtr[:,3:]=sc.fit_transform(xtr[:,3:])

print("X Train - \n",xtr)
print("Y Train - \n",ytr)
print("X Test - \n",xt)
print("Y Test - \n",yt)



